import { useEffect, useState, useSyncExternalStore } from "react";
import { ArrowLeft, ArrowRight, ArrowUpRight, Crosshair, ExternalLink, Search, X } from "lucide-react";
import { useHealth, useMarket, useOpportunity, type Analysis, type CrowdGap, type Detail, type Opportunity, formatNumber, formatPercent, formatIndex, sourceLabel } from "../lib/market";

const EXAMPLES = ["Running shoes UAE", "Dubai restaurants", "UAE skincare", "Luxury travel", "Coffee creators", "Fitness UAE"];
const DEMO_STEPS = ["Market map", "Opportunity", "Real evidence", "Creative DNA", "Campaign brief"];
const subscribe = (callback: () => void) => { window.addEventListener("popstate", callback); window.addEventListener("whitespace:navigate", callback); return () => { window.removeEventListener("popstate", callback); window.removeEventListener("whitespace:navigate", callback); }; };
const getURL = () => window.location.pathname + window.location.search;
function useURL() { return useSyncExternalStore(subscribe, getURL, () => "/"); }
function navigate(params: { q?: string; id?: string; demo?: boolean; step?: number }, replace = false) {
  const url = new URL("/", window.location.origin);
  if (params.q) url.searchParams.set("q", params.q);
  if (params.id) url.searchParams.set("id", params.id);
  if (params.demo) url.searchParams.set("demo", "1");
  if (params.step) url.searchParams.set("step", String(params.step));
  window.history[replace ? "replaceState" : "pushState"]({}, "", url.pathname + url.search);
  window.dispatchEvent(new Event("whitespace:navigate"));
  window.scrollTo({ top: 0, behavior: "smooth" });
}
function Logo({ onClick }: { onClick: () => void }) { return <a href="/" className="brand" data-testid="link-home" onClick={e => { e.preventDefault(); onClick(); }}><span className="brand-mark" aria-hidden="true"><i/><i/><i/><i/></span>WhiteSpace<span style={{ color: "var(--orange)" }}>.</span></a>; }
function Header({ onHome }: { onHome: () => void }) {
  return <div className="shell"><header className="topbar"><Logo onClick={onHome}/><nav className="nav-right" aria-label="Main navigation"><a className="nav-link" href="/#how-it-works" data-testid="link-how-it-works" onClick={e => { if (window.location.search) { e.preventDefault(); navigate({}); setTimeout(() => document.getElementById("how-it-works")?.scrollIntoView({ behavior: "smooth" }), 80); } }}>How it works</a><a className="nav-demo" href="/?demo=1" data-testid="link-start-demo" onClick={e => { e.preventDefault(); navigate({ q: "Running shoes UAE", demo: true }); }}>Take the 2-minute tour <ArrowUpRight size={12} style={{ display: "inline", verticalAlign: "-2px" }}/></a></nav></header></div>;
}
function SearchForm({ initial = "", compact = false, onSearch }: { initial?: string; compact?: boolean; onSearch: (q: string) => void }) {
  const [value, setValue] = useState(initial);
  useEffect(() => setValue(initial), [initial]);
  return <form className={compact ? "workspace-search" : "search-box"} onSubmit={e => { e.preventDefault(); if (value.trim()) onSearch(value.trim()); }}>
    {!compact && <Search size={18}/>}<input data-testid="input-market-query" aria-label="Search a market" placeholder="Search a market, audience, or category" value={value} onChange={e => setValue(e.target.value)} required />
    <button data-testid="button-analyze-market" type="submit" aria-label={compact ? "Analyze market" : undefined}>{compact ? <ArrowRight size={18}/> : <>Find the space <ArrowUpRight size={17}/></>}</button>
  </form>;
}
function Footer() { return <footer className="footer"><div className="shell footer-inner"><span className="brand"><span className="brand-mark" aria-hidden="true"><i/><i/><i/><i/></span>WhiteSpace.</span><span>Opportunity intelligence for the video internet.</span><span>Observed signals, not a prediction of virality.</span></div></footer>; }
function Landing({ onSearch }: { onSearch: (q: string) => void }) {
  const health = useHealth();
  return <div className="home">
    <section className="hero"><div className="hero-art" aria-hidden="true"><div className="ring"/><div className="ring"/><div className="ring"/><span className="art-dot a"/><span className="art-dot b"/><span className="art-dot c"/><span className="art-dot d"/></div><Header onHome={() => navigate({})}/><div className="shell hero-inner">
      <div className="hero-kicker eyebrow"><span className="tiny-line"/> Opportunity intelligence for the video internet</div>
      <h1>Stop chasing trends.<br/><em>Find the space</em><br/>everyone else missed.</h1>
      <p className="hero-sub">Find where attention is going before everyone else gets there. Ground your next move in observed video response, not another trend list.</p>
      <SearchForm onSearch={onSearch}/>
      <div className="suggestions"><span>TRY A MARKET</span>{EXAMPLES.map(x => <button key={x} data-testid={`button-example-${x.toLowerCase().replaceAll(" ","-")}`} onClick={() => onSearch(x)}>{x}</button>)}</div>
    </div></section>
    <div className="ticker"><div className="shell ticker-inner"><span><b>↗</b> Observe the market</span><span><b>↗</b> Locate the mismatch</span><span><b>↗</b> Build from evidence</span><span><b>↗</b> Make the move</span></div></div>
    <section className="home-section shell" id="how-it-works"><div className="eyebrow section-number">01 / A different way to see</div><div className="home-grid"><h2>Attention is not evenly distributed.</h2><p>Creators crowd the obvious formats. Audiences often respond somewhere else. WhiteSpace measures both sides of that equation across real Instagram and TikTok video data, so you can see the opening between what gets made and what actually moves people.</p></div><div className="principles"><div className="principle"><span className="eyebrow principle-index">01 — Measure</span><h3>Map the supply.</h3><p>See how much of the market is making each angle, measured as a share of observed video volume.</p></div><div className="principle"><span className="eyebrow principle-index">02 — Compare</span><h3>Read the response.</h3><p>Compare reach per follower and engagement per view against the market baseline, excluding the three biggest videos.</p></div><div className="principle"><span className="eyebrow principle-index">03 — Act</span><h3>Build with receipts.</h3><p>Move from an opportunity to source videos, creative patterns, candidate creators, and a platform-specific brief.</p></div></div></section>
    <section className="dark-band"><div className="shell home-grid"><div><div className="eyebrow section-number">02 / The opportunity map</div><h2>Look for the gap, not the spike.</h2><p>Our map puts content supply on one axis and relative audience response on the other. The upper-left is where an angle has less supply and stronger response. Every plotted point opens the evidence behind it.</p><p style={{ fontSize: 12 }}>Illustration only. Search a market to see measured points.</p></div><div className="sample-map" aria-hidden="true"><span className="sample-label">The space to investigate</span><span className="art-dot a"/><span className="art-dot b"/><span className="art-dot c"/><span className="art-dot d"/></div></div></section>
    <section className="home-section shell"><div className="eyebrow section-number">03 / Built for decisions</div><div className="home-grid"><h2>Not another dashboard full of noise.</h2><div><p>Start broad. Follow a measured angle into its source videos. Understand which creative choices recur, which creators have demonstrated relevant work, and how a campaign might translate across platforms.</p><p>WhiteSpace is a directional research tool. It does not claim to know what people will do next, and it does not predict virality.</p><p className="mono" style={{ fontSize: 11 }}>SERVICE STATUS · {health.isLoading ? "CHECKING" : health.isError ? "UNAVAILABLE" : health.data?.status?.toUpperCase() || "UNKNOWN"} {health.data ? `· ${health.data.mode}` : ""}</p></div></div></section>
    <section className="bottom-cta home-section"><div className="shell"><div className="eyebrow">The next good idea starts with a better question.</div><h2>What is your market missing?</h2><a href="/?demo=1" className="nav-demo" data-testid="link-bottom-demo" onClick={e => { e.preventDefault(); navigate({ q: "Running shoes UAE", demo: true }); }}>Explore a real query <ArrowUpRight size={14}/></a></div></section><Footer/>
  </div>;
}
function Provenance({ sources, scope, note, newestFetch }: { sources?: Record<string, number>; scope?: string; note?: string | null; newestFetch?: string | null }) {
  const stale = !!sources?.["stale-cache"];
  return <><div className="provenance" data-testid="status-provenance"><span className={`status-dot ${stale ? "warn" : ""}`}/><b>{stale ? "Stale cached data included" : sources?.live ? "Live Oriane data included" : sources?.cache ? "Cached Oriane data" : "Source status unknown"}</b><span className="divider">/</span><span>{sourceLabel(sources)}</span>{newestFetch && <><span className="divider">/</span><span>Newest source fetch {new Date(newestFetch).toLocaleDateString()}</span></>}</div>{scope && <div className="note" data-testid="text-evidence-scope"><b>Evidence scope.</b> {scope} {note ? ` ${note}` : ""} Directional comparison within indexed videos, not a representative consumer survey. WhiteSpace does not predict virality.</div>}</>;
}
function StateBox({ kind, message, retry }: { kind: "loading" | "error" | "empty"; message?: string; retry?: () => void }) {
  if (kind === "loading") return <div className="loading-layout" aria-label="Analyzing market"><div className="skeleton loading-map"/><div className="skeleton loading-side"/></div>;
  return <div className="state-box" data-testid={`status-${kind}`}><Crosshair size={30} strokeWidth={1.3}/><h2>{kind === "error" ? "We couldn't read this market." : "Nothing to plot yet."}</h2><p>{message || (kind === "error" ? "The source is unavailable right now. No results have been invented or substituted." : "No qualifying angles were returned for this query. Try another market to widen the evidence.")}</p>{retry && <button className="button-outline" data-testid="button-retry" onClick={retry}>Try again <ArrowRight size={14}/></button>}</div>;
}
function MapPanel({ analysis, onSelect }: { analysis: Analysis; onSelect: (id: string) => void }) {
  const [hover, setHover] = useState<string | null>(null);
  const points = analysis.opportunities;
  const maxSupply = Math.max(.02, ...points.map(p => p.supplyShare)) * 1.15;
  const maxResponse = Math.max(2, ...points.map(p => p.relativePerformance)) * 1.12;
  const pos = (p: Opportunity) => ({ left: `${Math.max(7,Math.min(94, p.supplyShare / maxSupply * 88 + 5))}%`, bottom: `${Math.max(8,Math.min(93, p.relativePerformance / maxResponse * 85 + 5))}%` });
  return <div className="panel" id="demo-map"><div className="panel-head"><h2>Supply × response</h2><span className="eyebrow" style={{ color: "#7b8592" }}>{points.length} measured angles</span></div><div className="panel-body"><div className="map-wrap"><div className="map-area"><span className="quadrant-label top-left">White space</span><span className="quadrant-label top-right">Proven, crowded</span><span className="quadrant-label bottom-left">Low signal</span><span className="quadrant-label bottom-right">Crowded, low response</span>{points.map((p, i) => <button key={p.id} type="button" className={`point ${p.quadrant}`} style={{ ...pos(p), width: 29 + Math.min(20,Math.sqrt(p.stats.n) / 4), height: 29 + Math.min(20,Math.sqrt(p.stats.n) / 4) }} title={`${p.name}: ${formatPercent(p.supplyShare)} supply, ${formatIndex(p.relativePerformance)} response`} aria-label={`Open ${p.name}, ${formatPercent(p.supplyShare)} supply, ${formatIndex(p.relativePerformance)} relative response`} data-testid={`button-map-point-${p.id}`} onFocus={() => setHover(p.id)} onBlur={() => setHover(null)} onMouseEnter={() => setHover(p.id)} onMouseLeave={() => setHover(null)} onClick={() => onSelect(p.id)}>{i + 1}</button>)}{hover && points.filter(p => p.id === hover).map(p => <div key={p.id} className="point-label" style={{ left: pos(p).left, bottom: `calc(${pos(p).bottom} + 20px)` }}>{p.name} · {formatIndex(p.relativePerformance)}</div>)}</div><div className="axis-x">Content supply →</div><div className="axis-y">Relative response →</div></div><div className="map-caption">Each point is an observed angle. Position reflects market supply share and relative performance; size loosely reflects matching video count. Select a point for source evidence.</div></div></div>;
}
function Metrics({ analysis }: { analysis: Analysis }) { return <div className="panel"><div className="panel-head"><h2>Market baseline</h2></div><div className="metric-stack"><div className="metric"><span>Indexed videos</span><strong data-testid="text-market-video-count">{formatNumber(analysis.baseline.n)}</strong><small>in measured scope</small></div><div className="metric"><span>Views / follower</span><strong data-testid="text-market-reach">{formatIndex(analysis.baseline.reach)}</strong><small>top 3 excluded</small></div><div className="metric"><span>Interactions / view</span><strong data-testid="text-market-engagement">{formatPercent(analysis.baseline.er)}</strong><small>top 3 excluded</small></div></div></div>; }
function OpportunityRows({ opportunities, onSelect }: { opportunities: Opportunity[]; onSelect: (id: string) => void }) { return <section className="list-section" id="demo-opportunity"><div className="section-title"><h2>Opportunity index</h2><small>Ranked by observed score · not a forecast</small></div>{opportunities.map((o, i) => <button key={o.id} type="button" className="opportunity-row" data-testid={`button-opportunity-${o.id}`} onClick={() => onSelect(o.id)}><span className="rank">{String(i+1).padStart(2,"0")}</span><span className="row-name"><strong>{o.name}</strong><small>{o.kind === "visual" ? "Visual match" : "Spoken / written match"} · {o.stage.toLowerCase()} · {formatNumber(o.stats.n)} videos</small></span><span className="row-stat hide-mobile">{formatPercent(o.supplyShare)}<small>Supply share</small></span><span className="row-stat hide-mobile">{formatIndex(o.relativePerformance)}<small>Response index</small></span><span className="score-pill">{o.score}</span><ArrowUpRight size={18}/></button>)}</section>; }
function GapCards({ gaps, inDetail = false }: { gaps: CrowdGap[]; inDetail?: boolean }) { return <section className="list-section"><div className="section-title"><h2>Where the crowd differs</h2><small>Market-level metadata comparisons</small></div>{inDetail && <p className="section-intro" data-testid="text-gap-scope" style={{ marginTop: 18 }}>These comparisons describe the whole measured market, not this selected opportunity. They are context for the category, not evidence that this angle has the same gap.</p>}<div className="gap-grid">{gaps.map(g => <article className={`gap-card ${g.isGap ? "is-gap" : ""}`} key={g.id} data-testid={`card-crowd-gap-${g.id}`}><span className="eyebrow" style={{ color: "var(--orange)" }}>{g.dimension} / {g.isGap ? "Observed gap" : "No gap detected"}</span><h3>{g.isGap ? `${g.winner.label} vs the default` : g.dimension}</h3><p>{g.headline}</p><small>{g.basis}. {g.detail}</small></article>)}</div></section>; }
function Method() { return <details className="method" data-testid="details-method"><summary>How are these numbers calculated?</summary><div className="method-content"><p><b>Supply:</b> matching angle videos divided by market videos. <b>Relative response:</b> √(reach index × engagement index), where each index compares the angle against the market. Reach is views per creator follower; engagement is interactions per view. Both exclude the three highest-viewed videos in each group.</p><p><b>Score:</b> 100 × √(clamp(0.5 + log₂(relative response), 0, 1) × 1/(1 + supply/0.01)) × confidence. Confidence accounts for sample size and concentration in the top three videos. This is deterministic and descriptive, not AI prediction.</p><p>Candidate creator fit is ranked from available evidence, not an endorsement. The data is directional and limited to the stated Oriane index scope. WhiteSpace does not predict virality.</p></div></details>; }
function AnalysisView({ query, onSearch, onSelect, analysis, isLoading, isError, error, retry }: { query: string; onSearch: (q:string)=>void; onSelect:(id:string)=>void; analysis?: Analysis; isLoading:boolean; isError:boolean; error:unknown; retry:()=>void }) {
  return <div className="workspace"><Header onHome={() => navigate({})}/><main className="shell workspace-main"><div className="breadcrumb"><a href="/" data-testid="link-breadcrumb-home" onClick={e => { e.preventDefault(); navigate({}); }}>HOME</a><span>/</span><span>MARKET ANALYSIS</span></div><div className="page-heading"><div><div className="eyebrow" style={{ color: "var(--orange)" }}>Market intelligence / 01</div><h1 data-testid="text-market-title">{analysis?.market?.label || query}</h1><p>Where observed audience response exceeds creator supply.</p></div><SearchForm compact initial={query} onSearch={onSearch}/></div>
  {isLoading ? <StateBox kind="loading"/> : isError ? <StateBox kind="error" message={error instanceof Error ? error.message : "The analysis request failed. Please retry."} retry={retry}/> : analysis ? <><Provenance sources={analysis.sources} scope={analysis.scope} note={analysis.note} newestFetch={analysis.newestFetch}/>{analysis.opportunities?.length ? <><div className="dashboard"><MapPanel analysis={analysis} onSelect={onSelect}/><Metrics analysis={analysis}/></div><OpportunityRows opportunities={analysis.opportunities} onSelect={onSelect}/></> : <StateBox kind="empty"/>}{analysis.crowdGaps?.length > 0 && <GapCards gaps={analysis.crowdGaps}/>}<Method/></> : <StateBox kind="empty"/>}</main><Footer/></div>;
}
function DetailView({ detail, analysis, query, onBack, retry, isLoading, isError, error }: { detail?: Detail; analysis?: Analysis; query:string; onBack:()=>void; retry:()=>void; isLoading:boolean; isError:boolean; error:unknown }) {
  return <div className="workspace"><Header onHome={() => navigate({})}/><main className="shell workspace-main"><div className="breadcrumb"><a href="/" data-testid="link-detail-home" onClick={e => { e.preventDefault(); navigate({}); }}>HOME</a><span>/</span><a href={`/?q=${encodeURIComponent(query)}`} data-testid="link-back-analysis" onClick={e => { e.preventDefault(); onBack(); }}>MARKET ANALYSIS</a><span>/</span><span>OPPORTUNITY</span></div>
  {isLoading ? <StateBox kind="loading"/> : isError ? <StateBox kind="error" message={error instanceof Error ? error.message : "The opportunity request failed. Please retry."} retry={retry}/> : detail ? <DetailContent detail={detail} analysis={analysis}/> : <StateBox kind="empty" message="This opportunity could not be found in the measured market."/>}</main><Footer/></div>;
}
function EvidenceBasis({ opportunity, video }: { opportunity: Opportunity; video: Detail["evidence"][number] }) {
  if (opportunity.kind === "visual") return <div className="match-basis" data-testid={`text-match-basis-${video.id}`}><b>WHY THIS MATCHED · FRAME SIMILARITY</b><span>{video.visualMatch != null ? `Oriane frame similarity score ${video.visualMatch.toFixed(2)} against the visual search prompt.` : "Returned by Oriane's visual similarity filter; per-video frame score unavailable."} Visual matches may be off-topic; inspect the source before using it.</span></div>;
  const matches = (opportunity.phrases || []).flatMap(phrase => {
    const where = [];
    if (video.caption?.toLowerCase().includes(phrase.toLowerCase())) where.push("caption");
    if (video.transcript?.toLowerCase().includes(phrase.toLowerCase())) where.push("transcript");
    return where.length ? [{ phrase, where: where.join(" and ") }] : [];
  });
  return <div className="match-basis" data-testid={`text-match-basis-${video.id}`}><b>WHY THIS MATCHED · TEXT SIGNAL</b><span>{matches.length ? <>Exact phrase “{matches[0].phrase}” in the {matches[0].where}.</> : "Oriane's phrase filter matched this video; the exact phrase is not visible in the returned caption or transcript."}</span></div>;
}
function DetailContent({ detail, analysis }: { detail: Detail; analysis?: Analysis }) {
  const { opportunity: o, evidence, dna, creators, brief } = detail;
  const references = brief.references?.filter(r => r.url && /^https?:\/\//i.test(r.url)) || [];
  return <><div className="detail-hero" id="demo-detail"><div><span className="eyebrow" style={{ color: "var(--orange)" }}>Opportunity #{detail.rank} / {o.stage} / {o.kind === "visual" ? "Visual signal" : "Language signal"}</span><h1 data-testid="text-opportunity-title">{o.name}</h1><p>{o.description}</p><div className="eyebrow" style={{ marginTop: 26, color: "#818997", lineHeight: 1.7 }}>DETECTION BASIS · {o.signal}</div></div><div className="detail-score"><span className="eyebrow">Observed opportunity score</span><strong data-testid="text-opportunity-score">{o.score}</strong><small>Supply, response & confidence. Not a prediction.</small></div></div>
  <div className="detail-stats"><div className="metric"><span>Content supply</span><strong data-testid="text-detail-supply">{formatPercent(o.supplyShare)}</strong><small>{formatNumber(o.stats.n)} matching videos</small></div><div className="metric"><span>Response index</span><strong data-testid="text-detail-response">{formatIndex(o.relativePerformance)}</strong><small>1.00× = market baseline</small></div><div className="metric"><span>Reach index</span><strong>{formatIndex(o.reachIndex)}</strong><small>views / follower vs market</small></div><div className="metric"><span>Engagement index</span><strong>{formatIndex(o.engagementIndex)}</strong><small>interactions / view vs market</small></div></div>
  <section className="why-panel" data-testid="section-why-opportunity"><div><span className="eyebrow">The reading / why this is an opportunity</span><h2>Supply and response diverge here.</h2><p data-testid="text-brief-opportunity">{brief.opportunity}</p></div><div className="why-aside"><span className="eyebrow">Current observed stage</span><strong>{o.stage}</strong><small>{o.momentum != null ? `Last-30-day creator supply pace: ${formatIndex(o.momentum)} relative to the market's own pace.` : "Recent creator supply pace unavailable for this angle."} This is a measurement of posts, not a forecast of audience demand.</small></div></section>
  <div style={{ marginTop: 30 }}><Provenance sources={detail.sources} scope={detail.scope} note={detail.note} newestFetch={detail.newestFetch ?? analysis?.newestFetch}/></div>
  {analysis?.crowdGaps?.length ? <GapCards gaps={analysis.crowdGaps} inDetail/> : null}
  <section className="detail-section" id="demo-evidence"><div className="section-title"><h2>The evidence</h2><small>{evidence.length} visible source videos · {detail.hiddenUnsafe} excluded for brand safety</small></div><p className="section-intro">Observed videos returned by Oriane for this angle. Sorted to surface strong organic evidence; paid or potentially boosted posts are labeled. Open a card to inspect the original post.</p>{evidence.length ? <div className="evidence-grid">{evidence.map(v => <article className="evidence-card" data-testid={`card-evidence-${v.id}`} key={v.id}>{v.url ? <a className="evidence-visual" href={v.url} target="_blank" rel="noopener noreferrer" data-testid={`link-evidence-video-${v.id}`} aria-label={`Open original video by ${v.creator.handle}`}>{v.thumbnail ? <img src={v.thumbnail} alt={`Video by ${v.creator.handle}`} loading="lazy"/> : <span className="evidence-fallback">{v.platform.slice(0,2).toUpperCase()}</span>}<span className="external"><ExternalLink size={14}/></span></a> : <div className="evidence-visual"><span className="evidence-fallback">{v.platform.slice(0,2).toUpperCase()}</span></div>}<div className="evidence-body"><h3>@{v.creator.handle} <span style={{ fontWeight: 400, color: "#8d95a0" }}>· {v.platform}</span></h3><p>{v.hook || v.caption || "No caption or opening transcript available."}</p><EvidenceBasis opportunity={o} video={v}/><div className="evidence-meta"><span>{formatNumber(v.views)} views</span><span>{formatIndex(v.reach)} reach</span><span>{formatPercent(v.er)} engagement</span></div>{(v.sponsored || v.likelyBoosted) && <span className="tag">{v.sponsored ? "Disclosed promotion" : "Possible boosted distribution"}</span>}</div></article>)}</div> : <StateBox kind="empty" message="No safe source videos were available for this angle."/>}</section>
  <section className="detail-section" id="demo-dna"><div className="section-title"><h2>Creative DNA</h2><small>Patterns from {dna.sample} evidence videos</small></div><p className="section-intro">Patterns observed in source posts, not rules for guaranteed results. Trait support is shown alongside each observation.</p><div className="dna-grid"><div className="dna-card"><h3>Recurring choices</h3>{dna.traits?.length ? dna.traits.map(t => <div className="trait" key={t.label}><span><strong>{t.label}</strong><br/><span style={{ color: "#717b89" }}>{t.value}</span></span><b>{t.support}/{t.of}</b></div>) : <p>Not enough source metadata to characterize this angle.</p>}</div><div className="dna-card"><h3>What opens the video</h3>{dna.hooks?.length ? dna.hooks.map(h => <div className="quote" key={h.videoId}><div>“{h.text}”</div><small style={{ color: "#8290a0" }}>@{h.handle} · {formatIndex(h.reach)} views/follower</small></div>) : <p>No opening transcript available in the evidence set.</p>}{dna.hookTypes?.length > 0 && <p><b>Observed hook types:</b> {dna.hookTypes.map(h => `${h.type} (${h.count})`).join(" · ")}</p>}</div><div className="dna-card"><h3>Audience voice</h3>{dna.audienceVoice?.length ? dna.audienceVoice.map((voice,i) => <div className="quote" key={`${voice.videoId}-${i}`}>“{voice.text}”<br/><small style={{ color: "#8290a0" }}>{voice.handle ? `@${voice.handle} · ` : ""}{formatNumber(voice.likes)} likes on source comment</small></div>) : <p>No qualifying comments were returned. We do not infer consumer opinions from missing comments.</p>}</div><div className="dna-card"><h3>Platform footprint</h3>{dna.platforms?.length ? dna.platforms.map(p => <div className="trait" key={p.platform}><span style={{ textTransform: "capitalize" }}>{p.platform}</span><b>{p.count} videos{p.medianDuration != null ? ` · ${Math.round(p.medianDuration)}s median` : ""}</b></div>) : <p>Platform breakdown unavailable.</p>}<p>This is a small evidence set, not a census of creative execution.</p></div></div></section>
  <section className="detail-section"><div className="section-title"><h2>Creator fit</h2><small>Candidate ranking from evidence · not endorsement</small></div><p className="section-intro">Fit combines execution against the creator's own median (35%), reach versus market (20%), engagement (15%), topic relevance (20%), and freshness (10%). Missing creator history reduces the evidence behind these components; a fit score is not an endorsement, availability check, or forecast.</p><div className="creator-list">{creators.length ? creators.map(c => <article className="creator" key={`${c.platform}-${c.handle}`} data-testid={`card-creator-${c.handle}`}><div className="avatar">{c.avatar ? <img src={c.avatar} alt=""/> : c.handle.slice(0,2).toUpperCase()}</div><div><h3>@{c.handle}</h3><small>{c.platform.toUpperCase()} · {formatNumber(c.followers)} FOLLOWERS · {c.baselineVideos} BASELINE VIDEOS</small><p>{c.why.length ? c.why.join(" ") : "Ranked from the available source evidence; creator baseline is limited."}</p>{c.videos?.some(v => v.url) && <div className="creator-videos"><span className="eyebrow">Supporting posts</span>{c.videos.filter(v => v.url && /^https?:\/\//i.test(v.url)).map(v => <a key={v.id} href={v.url!} target="_blank" rel="noopener noreferrer" data-testid={`link-creator-video-${v.id}`}>View {v.platform} post <ExternalLink size={12}/></a>)}</div>}</div><span className={`creator-score ${c.baselineVideos ? "" : "limited"}`} title={c.baselineVideos ? "Evidence-based fit score" : "Insufficient creator history for a reliable fit score"}>{c.baselineVideos ? c.fit : "Limited"}</span></article>) : <div className="note">No creators met the available evidence threshold for a grounded fit ranking.</div>}</div></section>
  <section className="detail-section" id="demo-brief"><div className="section-title"><h2>Campaign direction</h2><small>Actionable brief · based on observed evidence</small></div><div className="brief"><span className="eyebrow" style={{ color: "var(--lime)" }}>Cross-platform creative brief</span><h3>{brief.title}</h3><p>{brief.whyNow}</p><div className="brief-grid"><div className="brief-field"><b>Audience</b><span>{brief.audience}</span></div><div className="brief-field"><b>Premise</b><span>{brief.premise}</span></div><div className="brief-field"><b>Opening hook</b><span>{brief.hook}</span></div><div className="brief-field"><b>Opening shot</b><span>{brief.openingShot}</span></div><div className="brief-field"><b>Structure</b><span>{brief.structure.join(" → ")}</span></div><div className="brief-field"><b>Creator profile</b><span>{brief.creatorProfile}</span></div><div className="brief-field"><b>Tone</b><span>{brief.tone}</span></div><div className="brief-field"><b>Call to action</b><span>{brief.cta}</span></div></div>{brief.hookReference && <p className="mono" style={{ fontSize: 11 }}>HOOK REFERENCE · “{brief.hookReference.text}” — @{brief.hookReference.handle}</p>}<div className="eyebrow" style={{ color: "var(--lime)", marginTop: 25 }}>Platform adaptations</div><div className="platform-briefs">{brief.platforms.map(p => <div className="platform-brief" key={p.platform}><h4>{p.platform}</h4><p><b>Hook:</b> {p.hook}</p><p><b>Opening:</b> {p.opening}</p><p><b>Structure:</b> {p.structure.join(" → ")}</p><p><b>Caption:</b> {p.caption}</p><p><b>CTA:</b> {p.cta}</p><p><b>Pacing:</b> {p.pacing}</p><p><b>Basis:</b> {p.basis}</p></div>)}</div><div className="brief-references"><span className="eyebrow" style={{ color: "var(--lime)" }}>Source videos behind the direction</span>{references.length ? <div className="reference-links">{references.map(r => <a key={r.videoId} href={r.url!} target="_blank" rel="noopener noreferrer" data-testid={`link-brief-reference-${r.videoId}`}>@{r.handle} · {formatNumber(r.views)} views <ExternalLink size={13}/></a>)}</div> : <p>No source video URLs were provided with this brief. Review the evidence above where available.</p>}</div><p className="disclaimer">{brief.disclaimer} WhiteSpace does not predict virality. Verify source rights, creators and market fit before production.</p></div></section><Method/></>;
}
function DemoBanner({ query, id, step, analysis, detail }: { query: string; id: string; step: number; analysis?: Analysis; detail?: Detail }) {
  const next = () => {
    if (step === 0 && !analysis?.opportunities?.length) return;
    const firstId = id || analysis?.opportunities?.[0]?.id;
    if (step === 0 && firstId) navigate({ q: query, id: firstId, demo: true, step: 1 });
    else if (step < 4) navigate({ q: query, id: firstId, demo: true, step: step + 1 });
    else navigate({ q: query, id: firstId });
  };
  const previous = () => step === 1 ? navigate({ q: query, demo: true, step: 0 }) : navigate({ q: query, id, demo: true, step: Math.max(0,step - 1) });
  useEffect(() => { const target = ["demo-map","demo-detail","demo-evidence","demo-dna","demo-brief"][step]; const timer = setTimeout(() => document.getElementById(target)?.scrollIntoView({ behavior: "smooth", block: "start" }), 300); return () => clearTimeout(timer); }, [step, detail, analysis]);
  return <div className="demo-banner" data-testid="status-demo-tour"><div className="shell demo-inner"><span><b className="mono">GUIDED TOUR {step + 1}/5</b> &nbsp;·&nbsp; {DEMO_STEPS[step]} &nbsp;·&nbsp; Real query, actual returned data. About 2 minutes.</span><div className="demo-actions"><button data-testid="button-demo-previous" disabled={step === 0} onClick={previous}><ArrowLeft size={12} style={{ display:"inline",verticalAlign:"-2px" }}/> Back</button><button data-testid="button-demo-next" disabled={(step === 0 && !analysis?.opportunities?.length) || (step > 0 && !detail)} onClick={next}>{step === 4 ? "Finish tour" : "Next"} <ArrowRight size={12} style={{ display:"inline",verticalAlign:"-2px" }}/></button><button data-testid="button-demo-exit" onClick={() => navigate({ q: query, id: id || undefined })} aria-label="Exit guided tour"><X size={13}/></button></div></div></div>;
}
export default function Home() {
  const current = useURL();
  const params = new URLSearchParams(current.split("?")[1] || "");
  const demo = params.get("demo") === "1";
  const q = params.get("q") || (demo ? "Running shoes UAE" : "");
  const id = params.get("id") || "";
  const step = Math.max(0, Math.min(4, Number(params.get("step") || 0) || 0));
  const market = useMarket(q);
  const detail = useOpportunity(q, id);
  useEffect(() => { if (demo && !params.has("q")) navigate({ q: "Running shoes UAE", demo: true }, true); }, [demo, current]);
  const onSearch = (query: string) => navigate({ q: query });
  const onSelect = (opportunityId: string) => navigate({ q, id: opportunityId, demo, step: demo ? 1 : 0 });
  useEffect(() => { document.title = q ? `${id && detail.data ? detail.data.opportunity.name + " — " : ""}${q} | WhiteSpace` : "WhiteSpace — Find the space everyone else missed"; }, [q, id, detail.data]);
  if (current.split("?")[0] !== "/") return <div className="workspace"><Header onHome={() => navigate({})}/><main className="shell workspace-main"><StateBox kind="empty" message="This page does not exist. Return home to search a market."/></main><Footer/></div>;
  return <div className="app">{demo && <DemoBanner query={q} id={id} step={step} analysis={market.data} detail={detail.data}/>} {!q ? <Landing onSearch={onSearch}/> : id ? <DetailView query={q} detail={detail.data} analysis={market.data} isLoading={detail.isLoading} isError={detail.isError} error={detail.error} retry={() => detail.refetch()} onBack={() => navigate({ q, demo, step: 0 })}/> : <AnalysisView query={q} analysis={market.data} isLoading={market.isLoading} isError={market.isError} error={market.error} retry={() => market.refetch()} onSearch={onSearch} onSelect={onSelect}/>}</div>;
}